# -*- coding: utf-8 -*-

from odoo import api, models, fields, _


class FsmMaterialLine(models.Model):
    _name = 'lgps.fsm_material_line'
    _description = 'Fsm Material Line (parts)'

    name = fields.Char(
        required=True,
        string=_("Internal Id"),
        default="Autogenerated on Save",
    )

    observation = fields.Text(
        string=_('Description'),
        required=True
    )

    project_task_id = fields.Many2one(
        comodel_name="project.task",
        string=_('Fsm Task'),
        required=True,
    )

    product_id = fields.Many2one(
        comodel_name="product.product",
        string=_('Product'),
        required=True,
        domain="[('type', 'in', ['product', 'consu']), ('tracking', 'in', ['serial','lot'])]")

    lot_id = fields.Many2one(
        comodel_name="stock.lot",
        string=_('Lot/Serial'),
        domain="[('product_id','=', product_id)]",
    )

    # @api.onchange('product_id')
    # def _onchange_product_id(self):
    #     domain = {}
    #     if self.product_id:
    #         stock_location_id = self.env.ref('stock.stock_location_customers').id
    #         list_ids = []
    #
    #         # values = self.env['stock.production.lot'].search([
    #         #     ('product_id', '=', self.product_id.id),
    #         #     ('','', stock_location_id)
    #         # ])
    #         values = self.env['stock.quant'].search([
    #                 ('product_id', '=', self.product_id.id),
    #                 ('location_id', '=', stock_location_id)
    #             ])
    #
    #         for value in values:
    #             list_ids.append(value.lot_id.id)
    #
    #         self.lot_id = []
    #         domain = {'lot_id': [('id', 'in', list_ids)]}
    #
    #         return {'domain': domain}

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            seq = self.env['ir.sequence'].next_by_code('lgps.fsm_material_line') or _('New')
            vals['name'] = seq
            return super(FsmMaterialLine, self).create(vals)
