# -*- coding: utf-8 -*-

from odoo import api, models, fields, _


class Revision(models.Model):
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _name = 'lgps.revision'
    _description = _('Internal Revisions')

    name = fields.Char(
        required=True,
        string=_("Internal Id"),
        default="Autogenerated on Save",
    )

    observations = fields.Text(
        string=_('Observations'),
    )

    notes = fields.Html(
        string=_('Notes'),
    )

    project_task_id = fields.Many2one(
        comodel_name="project.task",
        string=_('Fsm Task'),
        required=True,
    )

    product_id = fields.Many2one(
        comodel_name="product.product",
        string=_('Product'),
        required=True,
        domain="[('type', 'in', ['product', 'consu']), ('tracking', 'in', ['serial','lot'])]")

    lot_id = fields.Many2one(
        comodel_name="stock.lot",
        string=_('Lot/Serial'),
        domain="[('product_id','=', product_id)]",
    )

    state = fields.Selection([
        ("new", "Nuevo"),
        ("review", "En Revisión"),
        ("resolution", "Resuelto")],
        string=_("Revision Status"),
        default="new"
    )

    resolution = fields.Selection([
        ("scrap", _("Scrap")),
        ("recycle", _("Recycle")),
        ("provider", _("Provider Warranty"))],
        string=_("Resolution"),
        default="recycle"
    )

    kanban_state = fields.Selection([
        ("normal", "In Progress"),
        ("blocked", "Blocked"),
        ("done", "Ready for next stage")],
        "Kanban State",
        default="normal"
    )

    color = fields.Integer()

    priority = fields.Selection([
        ('0', "Normal"),
        ('1', "Medium"),
        ('2', "High"),
        ('3', "Critical")],
        string='Priority',
        default='0'
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            seq = self.env['ir.sequence'].next_by_code('lgps.revision') or _('New')
            vals['name'] = seq
            return super(Revision, self).create(vals)

    def copy(self, default=None):
        default = dict(default or {})

        copied_count = self.search_count(
            [('name', '=like', u"Copy of {}%".format(self.name))])
        if not copied_count:
            new_name = u"Copy of {}".format(self.name)
        else:
            new_name = u"Copy of {} ({})".format(self.name, copied_count)

        default['name'] = new_name
        return super(Revision, self).copy(default)

    def action_set_done(self):
        for record in self:
            record.write({
                'state': 'resolution'
            })

    _sql_constraints = [
        ('name_unique',
         'UNIQUE(name)',
         "The revision id must be unique"),
    ]
