# -*- coding: utf-8 -*-
from odoo import api, models, fields, _
from odoo.exceptions import UserError
import logging
_logger = logging.getLogger(__name__)


class Tracking(models.Model):
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _name = 'lgps.tracking'
    _description = _('Lgps Tracking register')

    name = fields.Char(
        required=True,
        string=_("Tracking Id"),
        default="Autogenerated on Save"
    )

    client_id = fields.Many2one(
        comodel_name="res.partner",
        string=_("Client Account"),
        domain=[
            ('active', '=', True),
            ('is_company', '=', True)
        ],
        required=True,
    )

    device_id = fields.Many2one(
        comodel_name="lgps.device",
        string=_("Gps Device"),
        index=True,
        required=True,
        domain="[('id', 'in', filtered_devices_ids)]",
    )

    applicant = fields.Char(
        string=_("Applicant"),
    )

    state = fields.Selection(
        [
            ('registered', _('Registrado')),
            ('active', _('Activo')),
            ('paused', _('Detenido')),
            ('finished', _('Finalizado')),
            ('billed', _('Facturado')),
            ('cancelled', _('Cancelled')),
        ],
        string=_("State"),
        default="registered",
        tracking=True,
        required=True,
    )

    category = fields.Selection(
        [
            ('event', _('Per Event')),
            ('permanent', _('Permanent')),
            ('uninterrupted ', _('Uninterrupted')),
        ],
        string=_("Category"),
        default="event",
        required=True,
        index=True,
    )

    driver = fields.Char(
        string=_("Driver"),
    )

    phone = fields.Text(
        string=_("Phones"),
    )

    notifications = fields.Text(
        string=_("Email Notifications"),
    )

    notify = fields.Boolean(
        string=_("Notify Client"),
        default=False
    )

    initial_date = fields.Date(
        default=fields.Date.today,
        string=_("Initial Date"),
    )

    final_date = fields.Date(
        default=fields.Date.today,
        string=_("Final Date"),
    )

    origin = fields.Text(
        string=_("Origin"),
        required=True,
    )

    destination = fields.Text(
        string=_("Destination"),
        required=True,
    )

    route = fields.Text(
        string=_("Route"),
    )

    observations = fields.Text(
        string=_("Observations"),
    )

    emails = fields.Text(
        string=_("Additional Emails"),
    )

    start_date = fields.Datetime(
        string=_("Activity Started at"),
        readonly=True
    )

    end_date = fields.Datetime(
        string=_("Activity finished at"),
        readonly=True
    )

    tracking_log_ids = fields.One2many(
        comodel_name="lgps.tracking_logs",
        inverse_name="tracking_id",
        string=_("Logs"),
    )

    freight_weight = fields.Float(
        digits=(10, 1),
        string=_("Load Weight"),
        help=_("Freight weight in Kilos")
    )

    freight_dimensions = fields.Float(
        digits=(10, 1),
        string=_("Freight dimensions"),
        help=_("Freight dimensions in meters")
    )

    freight_cost = fields.Float(
        digits=(10, 2),
        string=_("Freight cost"),
        help=_("Freight costs")
    )

    comment_period = fields.Integer(
        string=_('Comment Period'),
        default=0,
    )

    active = fields.Boolean(default=True)

    vehicle_id = fields.Many2one(
        comodel_name="lgps.vehicle",
        string=_("Vehicle"),
        domain="[('id', 'in', filtered_vehicles_ids)]",
    )

    filtered_vehicles_ids = fields.Many2many(
        comodel_name="lgps.vehicle",
        compute="_compute_allowed_vehicle_ids"
    )

    filtered_devices_ids = fields.Many2many(
        comodel_name="lgps.device",
        compute="_compute_allowed_device_ids"
    )

    @api.depends("client_id")
    def _compute_allowed_vehicle_ids(self):
        log = []

        if self.client_id:
            log = self.env["lgps.vehicle"].search([['client_id', '=', self.client_id.id]])

        self.filtered_vehicles_ids = log

        return log

    @api.depends("client_id")
    def _compute_allowed_device_ids(self):
        log = []

        if self.client_id:
            log = self.env["lgps.device"].search([['client_id', '=', self.client_id.id]])

        self.filtered_devices_ids = log

        return log

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            seq = self.env['ir.sequence'].next_by_code('lgps.tracking') or '/'
            vals['name'] = seq
            return super(Tracking, self).create(vals)

    def button_do_active(self):
        for tracking in self:
            log_object = self.env['lgps.tracking_logs']
            employee = self.env['hr.employee'].search([('name', '=', self.env.user.name)])

            dictionary = {
                'name': 'Automatic Generated',
                'comment': 'Monitoreo Iniciado',
                'comment_date': fields.Datetime.now(),
                'employee_id': employee.id,
                'email_sent': '',
                'tracking_id': self.id,
                'vehicle_location': '',
            }
            device_log = log_object.create(dictionary)
            if device_log:
                tracking.state = 'active'
                tracking.start_date = fields.Datetime.now()

        return True

    def button_do_pause(self):
        for tracking in self:
            log_object = self.env['lgps.tracking_logs']
            employee = self.env['hr.employee'].search([('name', '=', self.env.user.name)])

            dictionary = {
                'name': 'Automatic Generated',
                'comment': 'Monitoreo Detenido',
                'comment_date': fields.Datetime.now(),
                'employee_id': employee.id,
                'email_sent': '',
                'tracking_id': self.id,
                'vehicle_location': '',
            }
            device_log = log_object.create(dictionary)
            if device_log:
                tracking.state = 'paused'

        return True

    def button_do_finish(self):
        for tracking in self:
            log_object = self.env['lgps.tracking_logs']
            employee = self.env['hr.employee'].search([('name', '=', self.env.user.name)])

            dictionary = {
                'name': 'Automatic Generated',
                'comment': 'Monitoreo Finalizado',
                'comment_date': fields.Datetime.now(),
                'employee_id': employee.id,
                'email_sent': '',
                'tracking_id': self.id,
                'vehicle_location': '',
            }
            device_log = log_object.create(dictionary)
            if device_log:
                tracking.state = 'finished'
                tracking.end_date = fields.Datetime.now()

        return True

    def button_do_cancel(self):
        for tracking in self:
            log_object = self.env['lgps.tracking_logs']
            employee = self.env['hr.employee'].search([('name', '=', self.env.user.name)])

            dictionary = {
                'name': 'Automatic Generated',
                'comment': 'Monitoreo Cancelado',
                'comment_date': fields.Datetime.now(),
                'employee_id': employee.id,
                'email_sent': '',
                'tracking_id': self.id,
                'vehicle_location': '',
            }
            device_log = log_object.create(dictionary)
            if device_log:
                tracking.state = 'cancelled'
                tracking.active = False
        return True

    def button_do_resume(self):
        for tracking in self:
            log_object = self.env['lgps.tracking_logs']
            employee = self.env['hr.employee'].search([('name', '=', self.env.user.name)])

            dictionary = {
                'name': 'Automatic Generated',
                'comment': 'Monitoreo Continuado',
                'comment_date': fields.Datetime.now(),
                'employee_id': employee.id,
                'email_sent': '',
                'tracking_id': self.id,
                'vehicle_location': '',
            }
            device_log = log_object.create(dictionary)
            if device_log:
                tracking.state = 'active'

        return True

