# -*- coding: utf-8 -*-
{
    'name': 'lgps',
    'description': 'Intralix module for internal processes',
    'author': 'Intralix',
    'application': True,
    'website': 'https://www.intralix.com',
    'category': 'Uncategorized',
    'version': '1.0.1',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'stock',
        'contacts',
        'account',
        'crm',
        'mail',
        'sale',
        'sale_management',
        'product',
        'resource',
        'project',
        'hr',
        'helpdesk',
        'industry_fsm',
    ],
    'demo':[
        'data/vehicle_stage.xml',
        'data/vehicle_types.xml',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/assign_accessories_wizard.xml',
        'wizard/cellchip_wizard.xml',
        'views/main_menu.xml',
        'data/vehicle_stage.xml',
        'data/vehicle_types.xml',
        'data/device_platforms.xml',
        'data/device_stage.xml',
        'views/vehicle_stage.xml',
        'views/vehicle_types.xml',
        'views/vehicle_kanban_view.xml',
        'views/vehicle.xml',
        'views/device_stage.xml',
        'views/platform_list.xml',
        'views/device.xml',
        'views/device_kanban_view.xml',
        'views/cellchip.xml',
        'views/accessory.xml',
        'views/tracking.xml',
        'views/tracking_logs.xml',
        'views/custom_partner.xml',
        'views/custom_crm_lead.xml',
        'views/custom_help_desk.xml',
    ],
}
