# -*- coding: utf-8 -*-
{
    'name': 'lgps',
    'description': 'Intralix module for internal processes',
    'author': 'Intralix',
    'application': True,
    'website': 'https://www.intralix.com',
    'category': 'Uncategorized',
    'version': '1.0.0',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'stock',
        'contacts',
        'account',
        'crm',
        'mail',
        'sale',
        'sale_management',
        'product',
        'resource',
        'project',
        'hr',
    ],
    'demo':[
        'data/vehicle_stage.xml',
        'data/vehicle_types.xml',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/main_menu.xml',
        'data/vehicle_stage.xml',
        'data/vehicle_types.xml',
        'views/vehicle_stage.xml',
        'views/vehicle_types.xml',
        'views/vehicle_kanban_view.xml',
        'views/vehicle.xml',
    ],
}
